"""initial migration

Revision ID: 1e83d7b55c6
Revises: None
Create Date: 2016-08-31 22:57:36.152762

"""

# revision identifiers, used by Alembic.
revision = '1e83d7b55c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
