"""change it

Revision ID: 3fa86a10a4b5
Revises: 5349c1cb8571
Create Date: 2016-09-03 11:10:13.558007

"""

# revision identifiers, used by Alembic.
revision = '3fa86a10a4b5'
down_revision = '5349c1cb8571'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
